---
    clickhouse:
      hosts:
        clickhouse-dev-1:
            ansible_host: 93.77.180.71
            ansible_host_internal: 10.0.1.12
            ansible_user: centos
    lighthouse:
      hosts:
        lighthouse-dev-1:
            ansible_host: 51.250.78.237
            ansible_host_internal: 10.0.1.23
            ansible_user: centos
    vector:
      hosts:
        vector-dev-1:
            ansible_host: 93.77.177.102
            ansible_host_internal: 10.0.1.32
            ansible_user: centos
